### ISSUE TITLE
Listen error :  make the device space full...

### ISSUE THREAD

**Issue by jasperchou** [toorop/go-pusher#13]
2018/01/03 14:36:55 Listen error :  json: cannot unmarshal object into Go struct field Event.data of type string
2018/01/03 14:36:55 Listen error :  EOF
2018/01/03 14:37:31 Listen error :  invalid character 'P' looking for beginning of value
2018/01/03 14:37:35 Listen error :  invalid character 'o' looking for beginning of value
2018/01/03 14:37:35 Listen error :  EOF
2018/01/03 14:37:35 Listen error :  EOF
2018/01/03 14:37:35 Listen error :  EOF
2018/01/03 14:37:35 Listen error :  EOF
2018/01/03 14:37:35 Listen error :  EOF
2018/01/03 14:37:35 Listen error :  EOF
2018/01/03 14:37:35 Listen error :  EOF
2018/01/03 14:37:35 Listen error :  EOF
2018/01/03 14:37:35 Listen error :  EOF
2018/01/03 14:37:35 Listen error :  EOF
2018/01/03 14:37:35 Listen error :  EOF
2018/01/03 14:37:35 Listen error :  EOF
2018/01/03 14:37:35 Listen error :  EOF
2018/01/03 14:37:35 Listen error :  EOF
2018/01/03 14:37:35 Listen error :  EOF
... so so so so many lines.....

just several seconds will get the warning ..."no space left on device"

**Comment by jasperchou** [comment]
```
for !c.Stopped() {
		var event Event
		err := websocket.JSON.Receive(c.ws, &event)
		if err != nil {
			if c.Stopped() {
				// Normal termination (ws Receive returns error when ws is
				// closed by other goroutine)
				return
			}
			log.Println("Listen error : ", err)
		} 
...
```

**Comment by toorop** [comment]
I do not have time to look right now (thank you spectrum && meltdown ... ). If you want to make a PR you are welcomed ;)

**Comment by jasperchou** [comment]
pls review.  :)
