### ISSUE TITLE
Connections not closed?

### ISSUE THREAD

**Issue by Deleplace** [toorop/go-pusher#7]
Hi, thanks for useful lib.

It looks like I can't close a Pusher connection after use (or I didn't find how).
The connections stats in my Pusher dashboard go up and never go down, until I kill program.
The `Client.ws *websocket.Conn` is unexported and its `Close` method is never called.
Also, there is a `Client.Stop chan bool` but it is unused.

Would you like me to give a try and make a PR?

**Comment by toorop** [comment]
@Deleplace if you want ;)
